### ISSUE TITLE
Virtual Machine Pre-installed with Tock and Toolchain

### ISSUE THREAD

**Issue by ppannuto** [helena-project/tock#109]
- [x] VM that can build Tock out of the box
- [ ] Be able to talk to hardware

**Comment by ppannuto** [comment]
How to get hardware, download software, install, etc. How to run tests that your install is correct.
    Details: USB drivers, sload program, etc.
    Necessary: Ubuntu, Mac OS X.
    Plus: Tell people with other Linux installs which packages to install. Linux VM.

**Comment by bradjc** [comment]
I think we're close on this one. Still need:
- Link to HW
- VM

**Comment by alevy** [comment]
@ppannuto is it still the case that the Vagrant image doesn't help with setting up serial ports, etc?

**Comment by ppannuto** [comment]
Correct, I'm not sure what the right thing to necessarily do there is.

The last time I looked into this it looked like Vagrant didn't have a great solution. You can absolutely tunnel them, but you can't configure it from Vagrant itself, have to go into your VirtualBox/VMWare/etc settings. Perhaps the best we can do for now is have a pointer in the Vagrant README to "follow these directions to get USB Serial for your VM environment" :/

**Comment by alevy** [comment]
Yeah, I think it's fine to tell people to figure it out based on their VM container. Can we close for now?
