### ISSUE TITLE
userland build needs to handle ~ expansion

### ISSUE THREAD

**Issue by ppannuto** [helena-project/tock#242]
@srohrer32 had

```
 3 TOCK_DIR = ~/git/tock                                                           
 4 TOCK_USERLAND_BASE_DIR = $(TOCK_DIR)/userland 
```

in the Makefile for his out-of-tree app, which caused all kinds of sadness like `/home/srohrer/git/embeddedMFCC/app/~/git/tock/userland/libtock/Makefile:`

It looks like neither `abspath` nor `realpath` in make expands tildes, so need to figure something out here

**Comment by alevy** [comment]
Does `~` ever work in Makefiles?

**Comment by ppannuto** [comment]
No idea, just documenting the issue for me to look at later.

My 5m of searching indicated that make doesn't play nicely with ~, but at
the same time, what Sam did doesn't seem unreasonable, it'd be good to find
a way to either support it, or at least detect / warn / fail if there's a ~

**Comment by alevy** [comment]
Got it, makes sense.

It seems reasonable to try and do the best possible within Makefile's capabilities, but if Makefile don't generally support it, my vote is against outsmarting it.

I don't know for sure either, I just know I've gotten in the habit of specifying `$(HOME)/...` when I pass variables to make.
