### ISSUE TITLE
nRF51822: Drop "APPS=c_blinky" from .travis.yml

### ISSUE THREAD

**Issue by lizardo** [helena-project/tock#31]
This will be done once c_hello is working for nRF51822 (which in turn depends on UART support).

Original discussion: https://github.com/helena-project/tock/pull/17#discussion-diff-49905753

**Comment by alevy** [comment]
I believe this is redundant since `.travis.yml` uses `c_blinky` for both platforms now. (blink seems like a better hello world for a microcontroller than hello world, anyway :smile:)
