### ISSUE TITLE
Unify syscall assembly implementations in src/arch/*/syscalls.S

### ISSUE THREAD

**Issue by lizardo** [helena-project/tock#32]
* [x] Fix cortex-m0 `__wait` implementation. The cortex-m0 and cortex-m4 differ in how they implement `__wait`. The m4 version is correct (see @alevy's comment below)

  * [x] Factor out common syscall code into assembly macros to make it more readable and to make it more clear that `__wait` is special on purpose.

(Original discussion: https://github.com/helena-project/tock/pull/17#discussion-diff-49906183)

**Comment by alevy** [comment]
As discussed on gitter:

> `wait` does need to push LR on the stack. Basically, the semantics of wait are that the kernel
> will push a callback on the application's stack, and in doing so, overwrite the app's LR register with
> the PC where `wait` was called.
> This is so that when the callback procedure returns, it returns to the location of the call to wait in
> the application

> So... the wait assembly is doing something a bit different than the other syscalls. When svc returns,
> it's actually going to be returning from the callback, not from the kernel.

> The place this happens in the kernel is here: https://github.com/helena-project/tock/blob/master/src/process/process.rs#L226

I'm marking this as a bug that should be fixed and rewording the issue description to pull out the action items.
