### ISSUE TITLE
Lingering Make Cleanups

### ISSUE THREAD

**Issue by ppannuto** [helena-project/tock#326]
Stuff noted while reviewing #325 that's orthogonal to #325

 - [x] https://github.com/helena-project/tock/pull/325/files#diff-28dd6258eca7e18969c0c42efa4ee139R8 is ugly. Don't check if we're in userland and bail, just don't have a file name `Makefile` (signpost does this right with `AppMakefile.mk` as the common root)
 - [x] Same with libtock Makefile
 - [x] Fixup BUILD*DIR family of variable names
 - [ ] Pretty sure there's a way to consolidate the .cc and .cpp recipes 
 - [x] Generally document all the make variables - mostly the stuff now in Configuration.mk (thanks Branden!)

**Comment by alevy** [comment]
`libtock` should be buildable independently, though. We _want_ to let someone just build `libtock.a`

**Comment by brghena** [comment]
That's not too hard to do. When I was changing how it built in #325 I had it building on its own. The trick is that it relies on the Configurations.mk and Helpers.mk files, but I don't know how to do the equivalent of a C Header Guard to stop them from being included twice.

**Comment by alevy** [comment]
Will it break if it gets included twice?

**Comment by alevy** [comment]
also, could just literally run `make` from libtock as part of the app build process

**Comment by ppannuto** [comment]
Include guards are pretty much the same in Make and C:

```make
ifndef TECHNICALLY_AN_ENVIRONMENT_VARIABLE_BUT_WHO_CARES
TECHNICALLY_AN_ENVIRONMENT_VARIABLE_BUT_WHO_CARES=1

...
endif
```

While I _think_ the stuff on common/helpers should be fine if included multiple times, no reason to further overcomplicate our lives

**Comment by ppannuto** [comment]
As for the running make, I had such hope for https://www.microsoft.com/en-us/research/wp-content/uploads/2016/03/hadrian.pdf when I saw a 2016 paper with that title, but no.

It remains the case that if you want to get dependency checking correct in make you have to figure out how to get it all to happen in one `make` process (or not use `make`... man can dream).

Should still be do-able to make libtock build independently however. And some of the macro tricks that the old GHC make system used look useful (`$$$$` here we come!)

**Comment by bradjc** [comment]
- [ ] Move Makefile.common to `/boards`

**Comment by brghena** [comment]
#325 should handle everything in this issue except consolidating the cc and cpp recipes

**Comment by ppannuto** [comment]
Upon some reading, some futzing, and some failures, I don't think there's actually a good / robust way to combine the .cc and .cpp rules. I pulled the ol' copy-paste trigger again to allow .cxx for C++ files as well in f9f8f4d7 and with that I think we can consider this closed.
