### ISSUE TITLE
Driver Number 36 Is Not Documented

### ISSUE THREAD

**Issue by bradjc** [helena-project/tock#339]
The driver num used in userland app `nrf51_temp_sensor` isn't documented on the Syscalls.md file. It's also not in libtock.

Should it be considered temporary? Do we have a mechanism for denoting a temporary driver number?

**Comment by alevy** [comment]
> Do we have a mechanism for denoting a temporary driver number?

Good one @bradjc

**Comment by alevy** [comment]
Fixed (by removal) in #444
