### ISSUE TITLE
nRF51822: Refactor platform init()

### ISSUE THREAD

**Issue by lizardo** [helena-project/tock#37]
See src/platform/storm/lib.rs for inspiration. static_init!() macro (ideally after moved to a common location) should be used for static buffer allocations.

At a minimum, mutable annotations should be removed where not necessary.

Original discussion: https://github.com/helena-project/tock/pull/17#discussion-diff-49907696

**Comment by alevy** [comment]
@lizardo it looks like you've basically done this in your branch. Let's not close this issue until we merge your branch, but I'm assigning you to it for now (just to record who is working on what).
