### ISSUE TITLE
Rewrite (part of) crt1.c in Rust

### ISSUE THREAD

**Issue by lizardo** [helena-project/tock#40]
There are a couple of "bare metal" projects that implement their reset handlers and ISR vectors in Rust as well. The generated code may not be super optimized as C or hand coded assembly, but this code is usually run/loaded once and thus not on the hot path.
- [x] SAM4L
- [ ] nrf51822

**Comment by alevy** [comment]
This is done for the SAM4L

**Comment by bradjc** [comment]
This was fixed, right?

**Comment by ppannuto** [comment]
Yeah, #649 removed the C code.
