### ISSUE TITLE
Consider removing `ENOACK`

### ISSUE THREAD

**Issue by ppannuto** [helena-project/tock#408]
See #401

**Comment by alevy** [comment]
@ppannuto do you mind making the case (independently of #401) here so it's easier to address the issue?

**Comment by ppannuto** [comment]
I read through and thought about this a bit, and I think I actually want to make the opposite case to myself. A missing acknowledgement is actually a pretty distinct and useful error (everything _we_ wanted to do send the packet worked just dandy, only no one [told us that they] heard it) that isn't really covered by existing error codes. It's not used much _now_, but it's probably a good error code to have around
