### ISSUE TITLE
Investigate need for built-in function replacements in crt1.c

### ISSUE THREAD

**Issue by lizardo** [helena-project/tock#41]
There is a TODO on the crt1.c but it is easier to track here.

Currently, we implement replacements for several built-in functions that could be provided by some runtime library (GCC or LLVM). It is not clear (at least for me), why they are needed. Are we missing linking to some library that could provide those functions?

**Comment by alevy** [comment]
I removed the built in functions in cf0de8fe934de5b92223ad48353f44102bae1fcd

I believe this is resolved except I've heard one report of `memclr` and `memclr4` not being available at kernel link-time. I'm guessing this has to do with the version of newlibc perhaps. but still investigating

**Comment by alevy** [comment]
Indeed it had to do with the version of newlibc. Since no one else has complained so far, I'm marking this issue closed.
