### ISSUE TITLE
Uncrustify still not working

### ISSUE THREAD

**Issue by brghena** [helena-project/tock#432]
~**Problem 1:** Checking for unstaged changes doesn't work~

~If I run `format_all.sh` on ubuntu 16.04 (version 0.59), it first checks rf233. It then finds changes to rf233.c and makes them inline. Then it moves to spi_byte, sees that there are unstaged changes to rf233.c and asks if I want to continue. Then it moves to lua-hello, sees that there are unstaged changes to rf233.c and asks if I want to continue...~

_Fixed by #481_

~**Problem 2:** I have changes to rf233.c at all~

~Since the build is currently passing, does this mean that different versions of uncrustify return different results?~

_Fixed by 6c43c5102_

~**Problem 3:** `format_all` repeatedly formats libraries~

_Fixed by 536ae5afa_

**Comment by bradjc** [comment]
It would be great to have:

```
$ cd /tock
$ make formatall
```

that runs all of the formatters. This would be useful for getting PRs ready.

**Comment by brghena** [comment]
I was thinking about this today, and it seems to me that they way to improve this is to separate `make format` for libraries from `make format` for example code, and have `make formatall` call both. Then developers can either run `make format` in the specific directory they want to handle, or `make formatall` in the root directory to do everything.

We could then create a  `userland/format_libraries.sh` (like `userland/examples/format_all.sh`) which handle the special-purpose logic of which libraries should be formatted with which tools. For now it would just be `libtock` with uncrustify, but you could imagine `lua53` being similarly formatted with its own tool in the future. `formatall` would then just call the library format script and the example app format script.

(Sidebar: I'm posting this here for @ppannuto instead of just doing it because I tried to implement it and failed. I don't even understand what makes the double-colon rule only apply to libtock right now...)
