### ISSUE TITLE
[build system: flash/program] Document the different programming methods

### ISSUE THREAD

**Issue by niklasad1** [helena-project/tock#574]
> We have a semi-standard (and wholly undocumented) idea of
"flash" => program over jtag
"program" => program over serial/bootloader

Where to put it?
Suggestions:
1. Board specific
2. Getting started guides
3. ???

Also, see [#571](https://github.com/helena-project/tock/pull/571) for a discussion regarding this.

**Comment by drahnr** [comment]
Definitley in the `Getting started`
