### ISSUE TITLE
nRF5x crate limits nRF52 to 4 GPIOTE channels

### ISSUE THREAD

**Issue by JayKickliter** [helena-project/tock#676]
nRF51 has 4 interrupt channels, but nRF52 has 8. So the nRF5x crate is falsely limiting nRF52 to 4.

The result is that when I try to enable more than 4 GPIO interrupts, I get a kernel panic in debug mode:

```
Kernel panic at vendor/tock/chips/nrf5x/src/gpio.rs:172:
        "attempt to shift left with overflow"
```

**Comment by niklasad1** [comment]
Ok, we need fix that!

Shall we pull out the entire GPIO driver from the nRF5X crate and define separate GPIO drivers in nRF51 and nRF52?

Or keep the current driver in nRF5X and complement with additional functionality in the nRF52 crate?

**Comment by JayKickliter** [comment]
Those were my questions. It could be a feature flag. I don't really have an opinion on it, but I'm going to have to fork Tock to get it working quickly.
