### ISSUE TITLE
Question, why not building userland library from source directly?

### ISSUE THREAD

**Issue by lygstate** [helena-project/tock#777]
Such as newlib and so on.
That's would make tock port to other platform other than Cortex-M4 easier.

**Comment by brghena** [comment]
Building newlib from source would take too long. Instead we reached the compromise of having a method in the repo for creating the pre-compiled libraries we use. For example: https://github.com/helena-project/tock/tree/master/userland/newlib The `build.sh` file has all of our configurations for newlib, just tweak it so it targets your architecture and build it with your favorite compiler.
