### ISSUE TITLE
[NRF52] Radio Registers broken

### ISSUE THREAD

**Issue by niklasad1** [helena-project/tock#835]
It looks like changes in the ```Register Interface``` broke the radio configuration for NRF52 i.e, ```matches``` is removed as I can tell.

```
error[E0599]: no method named `matches` found for type `kernel::common::regs::ReadWrite<u32, radio::Event::Register>` in the current scope
   --> /home/travis/build/helena-project/tock/chips/nrf52/src/radio.rs:678:27
    |
678 |         if regs.event_end.matches(Event::READY::SET) {
    |                           ^^^^^^^
```

**Comment by ppannuto** [comment]
`matches` got renamed to `matches_all`

There is also now a `matches_any` which you can use to check if any bit is set

**Comment by ppannuto** [comment]
I thought I got all of them in #827, apologies if I missed one, though somewhat distressing if Travis somehow missed it too...

**Comment by brghena** [comment]
How did this not get caught when the PR ran on Travis?

**Comment by bradjc** [comment]
Ok I think this is a merge/PR problem. Two PRs were merged, but Travis was not re-run on the second one (the nrf52 uart one), which if it had it would have noticed that it no longer compiled.
