### ISSUE TITLE
Explain platform-specific building for nRF

### ISSUE THREAD

**Issue by brghena** [helena-project/tock#94]
Need to edit [src/platform/nrf_pca10001/README.md](https://github.com/helena-project/tock/blob/master/src/platform/nrf_pca10001/README.md) to include details on how to build for the nRF51 Development Kit. I started it off with some details that I'm pretty sure are right.

**Comment by alevy** [comment]
They very close to accurate. I'll update + fill it in it soon

**Comment by phil-levis** [comment]
I have an NRF.md in the top directory of the devel branch.

Phil

**Comment by ppannuto** [comment]
Pretty sure that https://github.com/helena-project/tock/blob/master/boards/nrf51dk/README.md covers this sufficiently now
