### ISSUE TITLE
Any chat/irc channel to lurk on discussion around tock?

### ISSUE THREAD

**Issue by dpc** [helena-project/tock#98]

**Comment by alevy** [comment]
There is (now) a tock-dev Google group: https://groups.google.com/forum/#!forum/tock-dev which we'll be moving discussions that are not internal (i.e. not about strategizing for a paper we're writing or something like that).

I'm on Freenode on #tock. If you're on Freenode anyway it could be worth joining just in case (the rest of the developers have so far tried to avoid chat but might be a could place for everyone else)
